theme: jekyll-theme-slate
title: A code a day
author: melimelo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for a programming newbie. I'll be sharing my very slow progress with python programming, github and command line.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
